### ISSUE TITLE
User Input

### ISSUE THREAD

**Issue by Christo77793** [dotnet/csharp-notebooks#32]
Within these interactive notebooks, I am unable to find any examples on how to get a user's input? As I try Console.ReadLine() it proceeds to execute the next line of code. 

Example:
  string []answer = new string[10];
  
  for(int i = 0; i < answer.Length; i++)
  {
      answer[i]= Console.ReadLine();
  }

With this code, the cell keeps running for me with no prompt (like with Python) to enter an input.

**Comment by JakeRadMSFT** [comment]
@jonsequitur has this been considered?

Seems like it might be similar to: https://github.com/dotnet/interactive/pull/107

**Comment by jonsequitur** [comment]
Input requests are supported in VS Code and in Jupyter (though I just spotted a [bug](https://github.com/dotnet/interactive/issues/2044) in the latter).

![image](https://user-images.githubusercontent.com/547415/171736189-bc16b7ab-f6ed-486f-8682-5545d5a434fa.png)

<img width="627" alt="image" src="https://user-images.githubusercontent.com/547415/171736315-f15a464f-44f6-4d41-b18c-b77013e36910.png">

They can also be embedded in magic commands:

<img width="751" alt="image" src="https://user-images.githubusercontent.com/547415/171737349-bc4dee2c-52a0-452f-831b-ef922c82e823.png">


We've considered supporting `Console.ReadLine` because it's intuitive, but there are some complications such as lack of cancellation support, so we haven't found a satisfying solution.

**Comment by Christo77793** [comment]
Not to be presumptuous, but I think this needs to be included in the official docs in a way most people can be aware of it. Besides that, thank you very much, I truly appreciate you taking your time to respond to this.

**Comment by jcruzupr** [comment]
This post was helpful.
I hope the `Console.ReadLine` option is available in the near future.  I'll use the first option in the meantime.

**Comment by GoPapaSmurf** [comment]
Greetings, yes, that would be great if your could implement this essential feature. The description of CSharp Notebooks itself says "Notebooks are an _interactive_ tool", but there is no way to interact with it... When you want user input, Console.ReadLine(); doesn't work... When I try some code, I use Console.ReadLine(); all the time...
Regarding complications such as lack of cancellation support, possible trade-offs that come to mind are key combination, or time-out.
In the meantime, I'll use LINQPad, but I'd love to use CSharp Notebooks when the user can input data using Console.ReadLine();
Thank you 😉🙏
