### ISSUE TITLE
Link to Marketplace no longer finds Notebook extension to install

### ISSUE THREAD

**Issue by SFC-Sarge** [dotnet/csharp-notebooks#73]
Did you remove The Notebook extension for Visual Studio 2022 from the Marketplace? Where to get the latest version of the C# Notebook Extension for Visual Studio 2022?

**Comment by NotCoffee418** [comment]
It seems they're in the process of changing things around with the VS Code extension. I'm guessing it's likely related since i can find no other info about the VS2022 extention being discontinued or anything like that.

A few days ago a [blog post](https://devblogs.microsoft.com/dotnet/dotnet-interactive-notebooks-is-now-polyglot-notebooks/) came out about renaming the VSCode extension.
I'm not sure what that means for the visual studio version, but as of right now, searching for "notebook" or "polyglot" in the marketplace yields no results.

**Comment by JakeRadMSFT** [comment]
@SFC-Sarge @NotCoffee418 - Sorry that we haven't made it's deprecation clear. We'll work on messaging that to the community better.

The VS Notebook Extension was an experiment that didn't get as much adoption as we'd hoped. 

I'd love to hear your feedback on the VS Notebook extension and on the VS Code Polyglot notebooks! VS Code has the best .NET Notebook experience with Polyglot Notebooks.

https://github.com/dotnet/interactive#visual-studio-code


I apologize again for the abrupt deprecation of the VS Extension and hope the VS Code experience meets your needs. If not, let us know!

**Comment by SFC-Sarge** [comment]
@JakeRadMSFT 
I was working on replacing/modifying my [LinqLanguageEditor2022 ](https://marketplace.visualstudio.com/items?itemName=DannyMcNaught.LinqLanguageEditor)extension to use Notebooks and would like to continue this project, can you provide me a link to the source code for you VSIX package for the Notebook extension you were testing for Visual Studio 2022 so that I will not have to start from scratch with your package and this will allow me to maintain and support the use of a notebook in my extension?

**Comment by JakeRadMSFT** [comment]
@SFC-Sarge - I think having the discussion over in https://github.com/dotnet/interactive/issues/2475 makes sense.

.NET Interactive does a large majority of the heavy lifting.
